spring:
  cloud:
    config:
      native:
        search-locations: classpath:/shared #tells spring where to locate the config files
    profiles:
      active: native
    security:
      user:
        password: 1234
      server:
        port: 8888
